apiVersion: v1
kind: Pod
metadata:
  name: mfsada-gpu
spec:
  containers:
  - name: gpu-container
    image: nvidia/cuda:13.0.1-cudnn-devel-ubuntu24.04
    command: ["sleep", "3600"]
    resources:
      limits:
        cpu: 1
        memory: 1Gi
        nvidia.com/gpu: 1
      requests:
        cpu: 1
        memory: 1Gi
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: 2Gi
